name: Test and Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black isort flake8
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pytrilium/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 pytrilium/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: black --check pytrilium/
    
    - name: Import order check with isort
      run: isort --check-only pytrilium/
    
    - name: Test imports and basic functionality
      run: |
        python -c "from pytrilium.PyTrilium import PyTrilium; print('✅ Main import successful')"
        python -c "from pytrilium.PyTriliumAttachmentClient import PyTriliumAttachmentClient; print('✅ Attachment client import successful')"
        python -c "from pytrilium.PyTriliumAttributeClient import PyTriliumAttributeClient; print('✅ Attribute client import successful')"
        python -c "from pytrilium.PyTriliumBranchClient import PyTriliumBranchClient; print('✅ Branch client import successful')"
        python -c "from pytrilium.PyTriliumCalendarClient import PyTriliumCalendarClient; print('✅ Calendar client import successful')"
        python -c "from pytrilium.PyTriliumNoteClient import PyTriliumNoteClient; print('✅ Note client import successful')"

  version-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check version consistency
      run: |
        PYPROJECT_VERSION=$(grep "version = " pyproject.toml | sed 's/version = "\(.*\)"/\1/')
        USER_AGENT_VERSION=$(grep "pytrilium/" pytrilium/PyTriliumClient.py | sed 's/.*pytrilium\/\([0-9.]*\)".*/\1/')
        
        echo "pyproject.toml version: $PYPROJECT_VERSION"
        echo "User-Agent version: $USER_AGENT_VERSION"
        
        if [ "$PYPROJECT_VERSION" != "$USER_AGENT_VERSION" ]; then
          echo "❌ Version mismatch between pyproject.toml ($PYPROJECT_VERSION) and User-Agent ($USER_AGENT_VERSION)"
          echo "Please update both versions to match before releasing"
          exit 1
        fi
        
        echo "✅ Versions are consistent: $PYPROJECT_VERSION"